### ISSUE TITLE
Different output for Copy feature when the title of the card remains the same?

### ISSUE THREAD

**Issue by FlorentDancy** [Lujeni/matterllo#26]
Today, when a card is being copied, if the title is the same for the copied card, there's a duplication of the name of the card in the output.

I think it would be better to have a different output whether the name of the card is different or not.

_Exemple for different name:_
```
Card copied: "[Name of the card to be copied]" to "[Different name for the new card]" (To Dispatch list) by Someone
```

_Exemple for same name:_
```
Card copied: "[Name of the card to be copied]" copied in "[LIST NAME]" list) by Someone
```

What do you guys think about it?

**Comment by Lujeni** [comment]
@FlorentDancy Thanks dude :)

**Comment by FlorentDancy** [comment]
@Lujeni thank **you**! ;)
