### ISSUE TITLE
Not working by unknown reason

### ISSUE THREAD

**Issue by DaBlitzStein** [Lujeni/matterllo#29]
Hello. It looks like the software can't stablish the callbacks on trello, but it is an assumption because i don't really know.

Using built docker image.

```
  File "/usr/local/lib/python2.7/SocketServer.py", line 596, in process_request_thread
matterllo_1         |     self.finish_request(request, client_address)
matterllo_1         |   File "/usr/local/lib/python2.7/SocketServer.py", line 331, in finish_request
matterllo_1         |     self.RequestHandlerClass(request, client_address, self)
matterllo_1         |   File "/usr/local/lib/python2.7/SocketServer.py", line 652, in __init__
matterllo_1         |     self.handle()
matterllo_1         |   File "/usr/local/lib/python2.7/site-packages/django/core/servers/basehttp.py", line 159, in handle
matterllo_1         |     self.raw_requestline = self.rfile.readline(65537)
matterllo_1         |   File "/usr/local/lib/python2.7/socket.py", line 480, in readline
matterllo_1         |     data = self._sock.recv(self._rbufsize)
matterllo_1         | error: [Errno 104] Connection reset by peer

```

**Comment by Lujeni** [comment]
Hello @DaBlitzStein ,

It's seems the docker image is buggy.
I will dig this problem this week.

Keep in touch
Thanks

**Comment by Lujeni** [comment]
Hello @DaBlitzStein,

Did you use the localhost URL to test ? In this case, matterllo will create the trello fallback with localhost
Can you give me the docker logs pls also ?

Can you test with ngrok pls ?
- launch your docker container
 - ngrok http 8000
 - use the generated url

Thanks

**Comment by Lujeni** [comment]
Hello @DaBlitzStein,

friendly bump

THanks
