### ISSUE TITLE
Mattrello can`t log in

### ISSUE THREAD

**Issue by vladislav121** [Lujeni/matterllo#30]
Hello,

The keys token and API added, and matterllo can't get access to trello (see screenshot). 
in console error

unable to display board :: invalid key at https://api.trello.com/1/members/me/boards/?filter=all (HTTP status: 401)

in web 

invalid key at https://api.trello.com/1/members/me/boards/?filter=all (HTTP status: 401)

In the environment there are variables TRELLO_APIKEY and TRELLO_TOKEN.

How to be and what to do ?

PS thanks in advance

**Comment by Lujeni** [comment]
Hello @vladislav121,

Which install: heroku ? own server ?

You need to be login on Trello and follow this [link](https://trello.com/app-key) to generate key and token.

**Comment by vladislav121** [comment]
Hello @Lujeni ,

Own server (Centos 7 minimal).

The key and token generated in the system variables added.

![2017-01-18_22-16-41](https://cloud.githubusercontent.com/assets/25206953/22284088/0522027a-e2ff-11e6-96ce-2386bdc3649e.png)

**Comment by Lujeni** [comment]
Can you try with the library directly pls and gave me the output ? https://github.com/sarumont/py-trello

```python
from trello import TrelloClient 
trello_client = TrelloClient(api_key=TRELLO_APIKEY, token=TRELLO_TOKEN)
trello_client.list_boards()
```

**Comment by Lujeni** [comment]
@vladislav121 I modify the code to display a better error (wich display the token and co). Feel free to re-open the issue with your error.


![test](https://cloud.githubusercontent.com/assets/757902/22941362/795f49a4-f2e5-11e6-9825-96e34ed51180.png)
