### ISSUE TITLE
Doesn't Post to Mattermost

### ISSUE THREAD

**Issue by ak5** [Lujeni/matterllo#31]
I installed Matterlo via Docker and used the interface to configure my board and integration with Mattermost webhook.

Also tested Mattermost URL via `curl` from within the container and it works well.

When I do an action in Trello I see something is being posted to Matterlo:

```
[03/Feb/2017 10:03:50] "POST /callback/5/ HTTP/1.1" 200 0
```

But it is not posting to Mattermost - any idea what I am doing wrong?

**Comment by Lujeni** [comment]
Hello @ak5,

It's seems the docker image is buggy.
I will dig this problem this week.

Keep in touch
Thanks

**Comment by ak5** [comment]
I built the image via instructions in README. Let me know if I can provide you with anything to help

**Comment by ak5** [comment]
Hi, any updates?

**Comment by Lujeni** [comment]
Hello @ak5 ,

Did you use the localhost URL to test ? In this case, matterllo will create the trello fallback with `localhost`
Can you give me the docker logs pls also ?

Can you test with [ngrok](https://ngrok.com/) pls ?
- launch your docker container
- ngrok http 8000 
- use the generated url

**Comment by Lujeni** [comment]
Hello @ak5

Any update please?

**Comment by Tjird** [comment]
@Lujeni I have the same problem, if I trigger one or more of the triggers there doesn't came a post in mattermost. The interface says that the bridge is succesfully setup. Do you still need a error log?

**Comment by teodorkasap** [comment]
hi @Lujeni ,
i have the same problem. I see it has been a while since the last post.. have you been able to solve this?

**Comment by teodorkasap** [comment]
hi @Lujeni , I have tried with ngrok but the result is the same... matterllo registers the post request but it is not forwarded to mattermost hosted locally. My mattermost is ver 5.19

**Comment by teodorkasap** [comment]
hi @Lujeni maybe this could help: I have modified the Django version to Django==1.11 , which seems to be the latest supported LTS release for python 2.7... Do you think this could cause an issue? your help will be  appreciated.

**Comment by Lujeni** [comment]
@teodorkasap Hey thanks for the big delay of my response.
The latest version must fixed your problem.
