### ISSUE TITLE
Wrong message while moving cards

### ISSUE THREAD

**Issue by cguerrero** [Lujeni/matterllo#33]
When you move a card from one list to another list in the same board, Mattermost receives a message indicating that the card was unarchived, Which is wrong because it was just moved.
![screen shot 2017-02-08 at 9 45 45 am](https://cloud.githubusercontent.com/assets/928050/22744604/6cc5546a-ede3-11e6-87d6-3aa5b0dc254f.png)

**Comment by maralik** [comment]
I'm not getting notifications when I'm moving a card from one list to another at all. As well I don't see possibility to set enable this notification:
![snimek obrazovky 2017-02-15 v 11 41 07](https://cloud.githubusercontent.com/assets/905799/22970769/aa960d30-f373-11e6-8b36-c31eb9d9c953.png)

Is it even possible to configure it?

**Comment by cguerrero** [comment]
@maralik I just selected all notifications in the configuration and I can receive notifications when a card is moved to another list, however the message I receive is "unarchived Card" which si completely wrong.

**Comment by Lujeni** [comment]
Hey @cguerrero @maralik

The problem is fixed with the new version. Let me know if its good.
![test](https://cloud.githubusercontent.com/assets/757902/23067505/f526e3ee-f51f-11e6-97c5-28d4c9a968c6.png)

Another point is the `updateCard` hook, basically is handled multiple type of hook (was a mistake).
I update the list (little bit ugly :))
.![test2](https://cloud.githubusercontent.com/assets/757902/23067546/228d4580-f520-11e6-9f70-53c55f574fa5.png)

**Comment by cguerrero** [comment]
Thanks a lot @Lujeni I've already tried and it works perfectly for new integrations (new board in Trello and new Channel in Mattermost) but for any reason with previous boards and channels I receive two notifications:

* Unarchived Card
* Card Moved from List to List

And I don't really know why this is happening, I've remove the integration in Matterllo and created again, but the mistake keeps as you can see in the attached image the action "updateCard" is sent twice to Matterlo.

![screen shot 2017-02-17 at 9 03 42 am](https://cloud.githubusercontent.com/assets/928050/23070242/0afb9370-f4f0-11e6-8b4e-2d995b78069b.png)

Thanks a lot!

**Comment by Lujeni** [comment]
@cguerrero can you check in the django admin pannel the `bridge` model and check how many objects are present pls ?

**Comment by cguerrero** [comment]
Thanks @Lujeni there are several `bridges` models but there is only one per Channel/Webhook.
