### ISSUE TITLE
Posts are not posted by Matterllo by my own user

### ISSUE THREAD

**Issue by maralik** [Lujeni/matterllo#35]
I have configured user as it's not this screenshoot, but in mattermost I'm getting all posts posted by my name - is a bug or misconfiguration?

![screen capture 2017-02-14 v 13 53 48](https://cloud.githubusercontent.com/assets/905799/22929651/07b40b5a-f2bd-11e6-9e88-5dffb02f706b.png)

![screen capture 2017-02-14 v 13 52 52](https://cloud.githubusercontent.com/assets/905799/22929617/eae4c46a-f2bc-11e6-9f61-ba306fa1193b.png)

Thank you

**Comment by cguerrero** [comment]
@maralik you should read the documentation right in this section:

[https://docs.mattermost.com/developer/webhooks-incoming.html](url)

It's just misconfiguration in Mattermost!

**Comment by maralik** [comment]
Sorry, thanks.
