### ISSUE TITLE
Not Posting to MatterMost - Potential Configuration Issue

### ISSUE THREAD

**Issue by kashank** [Lujeni/matterllo#38]
I think that I'm missing a step in the configuration somewhere. I have matterllo setup on a linux server and can log into matterllo and create bridges to trello (the wizard successfully pulls in all of my boards), but whenever I trigger an action on trello (eg comment on a card), nothing happens on mattermost. 

Both mattermost and matterllo are on the same server and have their own nginx location entries where the entry proxies the requests. The proxy for matterllo looks like this:
` location /matterllo {
    proxy_http_version 1.1;
    proxy_cache_bypass $http_upgrade;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $http_host;
    proxy_pass http://127.0.0.1:8000;
}
`
In order to get the matterlo web interface to work, I _did_ have to modify urls.py under matterllo/matterllo/. 

Any thoughts as to what I'm doing wrong?

**Comment by Lujeni** [comment]
Hello @kshankin ,

do you any log from matterllo when you trigger a Trello action ?

Thanks

**Comment by s1lviu** [comment]
@kshankin do you have solved the problem? I think is the same like mine https://github.com/Lujeni/matterllo/issues/50

**Comment by FabrizioInfante** [comment]
@Lujeni I have the same error. Where can I find matterllo logs?
