### ISSUE TITLE
Heroku error

### ISSUE THREAD

**Issue by nommaz** [Lujeni/matterllo#39]
I am following the simple steps for heroku with ubuntu yet:

`heroku run python manage.py migrate`

fails with
```
...
  File "/app/matterllo/core/urls.py", line 4, in <module>
    from matterllo.core.views import (
  File "/app/matterllo/core/views/__init__.py", line 2, in <module>
    from board import *
ModuleNotFoundError: No module named 'board'
```

**Comment by nommaz** [comment]
i deleted the heroku app and also the /opt/matterlo folder and recreated everything to make sure i did not make a mistake but same exact result.

https://pure-spire-24631.herokuapp.com

**Comment by Lujeni** [comment]
Hi again @nommaz ,

I see your closed this issue, all is good now ?

Thanks

**Comment by nommaz** [comment]
Yes I self hosted. Gave up on heroku.
