### ISSUE TITLE
Card unarchived called incorrectly

### ISSUE THREAD

**Issue by nommaz** [Lujeni/matterllo#41]
I have noticed following events are reflected to mattermost as "Card unarchived"

- Add/remove due date completed checkbox
- Add/remove the photo being a card cover

**Comment by Lujeni** [comment]
Thanks @nommaz

**Comment by josh-torrey** [comment]
Similar bug over here, but am seeing the "Card unarchived" event when moving between lists.

**Comment by Lujeni** [comment]
Hi @josh-torrey

Can you try with the last version pls?

**Comment by josh-torrey** [comment]
@Lujeni - I am working off of the latest (Oct 4) version. Downloaded and deployed to Heroku yesterday.
