### ISSUE TITLE
Photo attachments

### ISSUE THREAD

**Issue by nommaz** [Lujeni/matterllo#42]
When a photo is added to trello card the update shows the long photo url and then the photo itself.

Making the photo clickable instead with the url not visible to user would be nicer

**Comment by nommaz** [comment]
Migrated post from Slack to Mattermost (originall posted by Trello->Slack power-up) image has no url.

Only including the image part from the two posts:

```
<div class="attachment__body attachment__body--no_thumb">
<img class="attachment__image" src="https://trello-attachments.s3.amazonaws.com/5407224578ac8505d323de03/588738ad490862f68b087eed/6fc8b37ee5721744213c59c0e11e9cc4/favicon-github-32.png">
</div>
```

Mattrello post image has url showing:
```
<a class="theme markdown__link" href="https://trello-attachments.s3.amazonaws.com/5407224578ac8505d323de03/588738ad490862f68b087eed/6fc8b37ee5721744213c59c0e11e9cc4/favicon-github-32.png" rel="noreferrer" target="_blank">
https://trello-attachments.s3.amazonaws.com/5407224578ac8505d323de03/588738ad490862f68b087eed/6fc8b37ee5721744213c59c0e11e9cc4/favicon-github-32.png</a>
```

**Comment by Lujeni** [comment]
Hello,

I removed the long attachment url (attachment could be another type, not only picture).

The title of the attachment is clickable also

Thanks
