### ISSUE TITLE
Label and member

### ISSUE THREAD

**Issue by nommaz** [Lujeni/matterllo#43]
Cannot get the add member action to fire even though I have it in the bridge. All other events i need work fine.

**Comment by Lujeni** [comment]
Hi @nommaz 

Thanks again for this issue.

I test with the current master branch and seems to works

```
subscribe for this action :: board=tutorial-board-start-here :: action=addMemberToCard
[04/Oct/2017 13:17:18] "POST /callback/92/ HTTP/1.1" 200 0
```

![test](https://user-images.githubusercontent.com/757902/31177797-61ccec54-a917-11e7-94ea-e8864c4ad91f.png)

Feel free to re-open an issue with more details if you encounter the problem.

Thanks
