### ISSUE TITLE
Unable to read boards

### ISSUE THREAD

**Issue by cguerrero** [Lujeni/matterllo#47]
Hi, 

I'm unable to read boards, I've carefully followed the instructions to make it work, but every time I wan to read my boards I receive the message:

"unable to display board :: 'X509' object has no attribute '_x509'"

Any ideas to solve it? I've been using the tool for a long time but I needed to migrate my server and the problem started.

Hope you can help me!

**Comment by Lujeni** [comment]
Hello @cguerrero,

Maybe there is a bug with a board name when the code try to `slugify`.
Can you give me the board if it's not confidential ?

Thanks

**Comment by cguerrero** [comment]
Thanks @Lujeni the problem is that I don't know which one has the issue, that's all the information I get in console.

**Comment by thend20** [comment]
I have the same problem.  When I load the admin page and I click Start, I'm greeted with the x509 error, and nothing ever loads.

**Comment by Lujeni** [comment]
I need to dig to find the problem.
- Are you under `http` ?
- can you give me your `requests` version pls ?

Sorry for the delay
