### ISSUE TITLE
result=False when uWSGI & nginx

### ISSUE THREAD

**Issue by s1lviu** [Lujeni/matterllo#50]
When I run the server manually, without nginx, the hooks are creating with success.

But, when I try to put the things on nginx.. 
```
delete trello hook :: result=[]
create trello hook :: callback=http://matterllo.x.com:8080/callback/1/ :: board=amazon-argila :: result=False
create trello hook :: callback=http://matterllo.x.com:com:8080/callback/2/ :: board=apiscrm :: result=False
create trello hook :: callback=http://matterllo.x.com:8080/callback/2/ :: board=apiscrm :: result=False
```

nginx config:

```
server {
    listen 8080;
    server_name matterllo.x.com;

   location / {
	include uwsgi_params;
        uwsgi_ignore_client_abort on;
	uwsgi_pass unix:/home/silviu/uwsgi/trello.sock;
   }
}
```
I'm stuck for few hours at this and I don't know what's the problem. 
Thanks!

**Comment by s1lviu** [comment]
@Lujeni seems to be a 400 Bad Request, but I can't find the problem until now. :(

**Comment by Lujeni** [comment]
@s1lviu Sorry for the delay, I was focus on other issues.

Do you have your `nginx` logs pls?
