### ISSUE TITLE
Invalid return_url

### ISSUE THREAD

**Issue by arnaudbagnis** [Lujeni/matterllo#56]
Hello, 
I generated api token & token thanks that https://trello.com/app-key/
I followed this instruction

`heroku config:set TRELLO_APIKEY=<your_api_key>`
`heroku config:set TRELLO_TOKEN=<your_token>`

But when I click to login to trello I have a error 

> Invalid return_url

**Comment by Lujeni** [comment]
@arnaudbagnis Hello thanks for your issue and sorry for the big delay.

The latest version must fix your problem.
Feel free to reopen this issue if not
