### ISSUE TITLE
Fresh install fails on Django-2.2.10

### ISSUE THREAD

**Issue by Dekat** [Lujeni/matterllo#61]
I get this error when installing Matterllo : 
```
File "matterllo/matterllo/urls.py", line 7, in <module>
    url(r"^login/$", auth_views.login, name="login"),
AttributeError: module 'django.contrib.auth.views' has no attribute 'login'
```
After executing this : `python manage.py migrate`

If I rollback this commit 9c107d59b3a0acf11a74c48c9b47b1bb989a26d2, from pull-request #60, it works again !

**Comment by QuentinBibas** [comment]
HI!

I'm having the same issue / error on a fresh install.
Tried with both Django 2.2.10 and 2.2.13
How did you manage to get it to work ?

**Comment by Lujeni** [comment]
Hey thanks for the issue.
I'll take a look this week end and fix the issues.

I'm going to take this opportunity to do a little housework (cleanup, fix and kubernetes deployment)
