### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by kfitz** [Lujeni/matterllo#63]
Hi! I'm running a Mattermost instance in a Docker instance on Reclaim Cloud, and am running into trouble with the Matterllo startup process. I got through retrieving and creating the image fine, and after a good deal of trial and error, I got through the "run the container" step, which returned a long string that I take to be the container ID. But then I get stuck on the third step:

`# apply the migration`
`$ docker exec matterllo python manage.py loaddata admin`

-- the result of which is an error message saying that `Container $longstring is not running`. But when I attempt to re-run the run command, it tells me that /matterllo is already in use by container $longstring. So based on some searching around, I've figured out that I can start the container with `sudo docker start $longstring` and then run the command above, but when I do I get this error:

`OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: \"python\": executable file not found in $PATH": unknown`

I'm more or less blundering around in the dark at this point, so if you have any suggestions I'd be grateful...

**Comment by Lujeni** [comment]
@kfitz Hello Thanks for your issue and sorry for the delay.

I did few refactoring this week, the build must be ok.

Feel free to reopen this issues if not.

**Comment by kfitz** [comment]
Thank you! On running `python manage.py migrate` I get an error: `ModuleNotFoundError: No module named '_sqlite3'`. sqlite3 is installed.

**Comment by kfitz** [comment]
Ignore the comment above; after some machinations I managed to get python and sqlite properly updated, and matterllo is now installed. I can get the server running but am puzzling through configuration now...
